version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.simplejavamail:simple-java-mail
    versions:
    - 6.4.5
    - 6.5.1
  - dependency-name: org.eclipse.jetty:jetty-alpn-conscrypt-server
    versions:
    - 11.0.0
  - dependency-name: org.eclipse.jetty.http2:http2-server
    versions:
    - 11.0.0
