remote_theme: pmarsceill/just-the-docs

title: SimpleWebsite
description: A basic web site framework library
baseurl: "/simplesite"
url: "https://kingtux.dev"

aux_links:
  "SimpleSite on GitHub":
    - "https://github.com/wherkamp/simplesite"
  "JavalinVC":
    - "https://kingtux.dev/javalinvc/"